language: node_js

node_js:
  - "0.10"

addons:
  sauce_connect: true

before_install:
  - sudo apt-get install nginx
  - nginx -p . -c cocproxy.nginx.conf
  - npm install -g protractor

script:
  - protractor protractor.conf.js
